name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m pytest backend/tests/ -v

    - name: Test backend startup
      run: |
        cd backend
        python -c "import asyncio; import os; os.environ['AI_SITE_GENERATOR_MOCK'] = 'true'; from app import app; import uvicorn; import threading; import time;\ndef run_server():\n    uvicorn.run(app, host='0.0.0.0', port=8000)\nthread = threading.Thread(target=run_server, daemon=True)\nthread.start()\ntime.sleep(2)\nprint('✅ Backend started successfully')"
